#!/usr/bin/env python3
"""Build the vendorable ZeroNotebookLM single-file artifact.

The generated file is stdlib-only. It embeds the current ``notebooklm`` package
and committed ``compat`` fixtures as a compressed payload. At runtime it extracts
the payload into a temporary directory, adds that directory to ``sys.path``, and
dispatches to ``notebooklm.cli.console``.

This is intentionally a release-candidate/closed-system artifact builder, not a
live NotebookLM smoke runner. The embedded CLI retains the same auth/live gates as
the package implementation.
"""

from __future__ import annotations

import argparse
import base64
import json
import stat
import textwrap
import zlib
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "singlefile" / "zero_notebooklm.py"
INCLUDE_ROOTS = (
    REPO_ROOT / "notebooklm",
    REPO_ROOT / "compat",
)
INCLUDE_SUFFIXES = {".py", ".txt", ".json", ".md"}
EXCLUDE_PARTS = {"__pycache__", ".pytest_cache"}


def _iter_payload_files() -> Iterable[Path]:
    for root in INCLUDE_ROOTS:
        if not root.exists():
            continue
        for path in sorted(
            root.rglob("*"), key=lambda p: p.relative_to(REPO_ROOT).as_posix()
        ):
            rel = path.relative_to(REPO_ROOT)
            if any(part in EXCLUDE_PARTS for part in rel.parts):
                continue
            if not path.is_file():
                continue
            if path.suffix not in INCLUDE_SUFFIXES:
                continue
            yield path


def build_payload() -> str:
    entries: list[tuple[str, str]] = []
    for path in _iter_payload_files():
        rel = path.relative_to(REPO_ROOT).as_posix()
        encoded = base64.b64encode(path.read_bytes()).decode("ascii")
        entries.append((rel, encoded))
    raw = json.dumps(
        entries, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    ).encode("utf-8")
    compressed = zlib.compress(raw, level=9)
    return compressed.hex()


def render_artifact(payload_hex: str) -> str:
    wrapped_payload = "\n".join(textwrap.wrap(payload_hex, width=88))
    return f'''#!/usr/bin/env python3
"""Vendored ZeroNotebookLM single-file CLI artifact.

Generated by ``scripts/build_singlefile.py``. This file is self-contained: it
extracts an embedded stdlib-only package/fixture payload into a temporary
runtime directory and dispatches to ``notebooklm.cli.console``. It does not read
site-packages, browser stores, keychains, or live NotebookLM state by default;
those boundaries are enforced by the embedded CLI.
"""

from __future__ import annotations

import base64
import json
import sys
import tempfile
import zlib
from pathlib import Path

_PAYLOAD_HEX = """\
{wrapped_payload}
"""


def _extract_payload(root: Path) -> None:
    raw = zlib.decompress(bytes.fromhex(_PAYLOAD_HEX))
    entries = json.loads(raw.decode("utf-8"))
    for rel, encoded in entries:
        if rel.startswith("/") or ".." in Path(rel).parts:
            raise RuntimeError("unsafe embedded payload path")
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(base64.b64decode(encoded.encode("ascii")))


def main(argv: list[str] | None = None) -> int:
    sys.dont_write_bytecode = True
    with tempfile.TemporaryDirectory(prefix="zero-notebooklm-singlefile-") as tmp:
        root = Path(tmp)
        _extract_payload(root)
        sys.path.insert(0, str(root))
        try:
            from notebooklm.cli import console

            return int(console(argv))
        finally:
            try:
                sys.path.remove(str(root))
            except ValueError:
                pass


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
'''


def build(out: Path = DEFAULT_OUT) -> Path:
    payload = build_payload()
    rendered = render_artifact(payload)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8", newline="\n")
    mode = out.stat().st_mode
    out.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="build_singlefile.py")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="output artifact path")
    args = parser.parse_args(argv)
    out = build(Path(args.out))
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
